# The Docker image that will be used to build your app
image: centos:centos8
create-pages:
  script:
    - echo "Deploying to GitLab Pages.."
    - mkdir -p public
    - cp index.html public/index.html
  artifacts:
    paths:
      - public
  only:
    - pages
